people/urls.py
from django.conf.urls.defaults import *
from wangji.people import views

urlpatterns = patterns('',
	#(r'^$', 'wangji.people.views.index'),
	(r'^(?P<object_id>\d+)/message/$', 'wangji.people.views.message'),
	(r'^(?P<object_id>\d+)/$', 'wangji.people.views.profile'),
	(r'^(?P<object_id>\d+)/(?P<shorsa>[a-z]{5})/$', 'wangji.people.views.detail'),
)

urls.py
from django.conf.urls.defaults import *
#from pinax.apps.account import urls

from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from wangji.sharesite.models import Onesite

info_dict = {
	'queryset': Onesite.objects.all(),
}

urlpatterns = patterns('',
    # Example:
    # (r'^wangji/', include('wangji.foo.urls')),
    # Uncomment the next line to enable the admin:
	(r'^admin/', include(admin.site.urls)),

	(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT, 'show_indexes': True}),

	#(r"^account/", include("pinax.apps.account.urls")),
	(r'^account/', include('wangji.account.urls')),
	(r'^people/', include('wangji.people.urls')),
	(r'^sharesite/', include('wangji.sharesite.urls')),
    (r'^(?P<tag_id>\d+)/$', 'wangji.sharesite.views.tag'),
	(r'^siteinfo/$', 'wangji.sharesite.option.siteinfo'),
	(r'^$', 'wangji.sharesite.views.index'),

	(r'^snooker/$', 'wangji.sharesite.snooker.snooker'),
	(r'^sjtu/$', 'wangji.sharesite.snooker.index'),
	(r'^invite/$', 'wangji.sharesite.snooker.invite'),
	(r'^snooker/about/$', 'wangji.sharesite.snooker.about'),
	(r'^snooker/players/$', 'wangji.sharesite.snooker.players'),
	(r'^snooker/clubs/$', 'wangji.sharesite.snooker.clubs'),
	(r'^snooker/voice/$', 'wangji.sharesite.snooker.voice'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

people/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

#user information 
#it contains accounts, mail, thirds-app, MessageBoard, Sharesite
#class People(models.Model):
#	username = models.CharField(max_length=20)
#	password = models.CharField(max_length=20)

#user's messageboard
class MessageBoard(models.Model):
	account = models.ForeignKey(User)
	user = models.CharField(max_length=20)
	pub_date = models.DateTimeField('date published')
	star = models.IntegerField()
	agree = models.IntegerField()
	content = models.CharField(max_length=500)

#user's mail
#class Mail(models.Model):
#	pass

sharesite/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __unicode__(self):
		return self.question

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice = models.CharField(max_length=200)
	votes = models.IntegerField()
	def __unicode__(self):
		return self.choice
	def was_published_today(self):
		return self.pub_date.date() == datetime.date.today()

class Onesite(models.Model):
	user = models.ForeignKey(User)
	tags = models.CharField(max_length=50)
	title = models.CharField(max_length=50)
	logo = models.CharField(max_length=100)
	domain = models.CharField(max_length=50)
	value = models.CharField(max_length=50)
	info = models.CharField(max_length=500)
	skill = models.CharField(max_length=500)
	shareusers = models.CharField(max_length=1000)
	pub_date = models.DateTimeField('date published')

class Comments(models.Model):
	onesite = models.ForeignKey(Onesite)
	user = models.CharField(max_length=20)
	pub_date = models.DateTimeField('date published')
	star = models.IntegerField()
	agree = models.IntegerField()
	content = models.CharField(max_length=500)

people/views.py
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.contrib.auth.models import User
from wangji.people.models import MessageBoard
from django.contrib.auth import logout
from wangji.sharesite.models import Onesite
import time, string

def index(request):
	object_list = User.objects.all().order_by('-date_joined')[:5]
	return render_to_response('people/people_list.html', {'object_list': object_list})

def profile(request, object_id):
	u = get_object_or_404(User, pk=object_id)
	site_list = u.onesite_set.all().order_by('-pub_date')
	return render_to_response('people/people_profile.html',{'object':u, 'site_list': site_list}, context_instance=RequestContext(request))

def detail(request,object_id, shorsa):
	u = get_object_or_404(User, pk=object_id)
	if (cmp(shorsa, 'saved') == 0):
		site_list = u.onesite_set.all().order_by('-pub_date')
		return render_to_response('people/people_profile.html',{'object':u, 'site_list': site_list}, context_instance=RequestContext(request))
	if (cmp(shorsa, 'share') == 0):
		site_list = Onesite.objects.filter( shareusers__contains = ('*' + str(u.id) + '*' )).order_by('-pub_date')
		return render_to_response('people/people_profile.html',{'object':u, 'site_list': site_list}, context_instance=RequestContext(request))


def message(request, object_id):
	p = get_object_or_404(User, pk=object_id)
	u = User()
	c = MessageBoard(user=u,star=3,agree=1,content=request.POST['info'])
	c.account = p
	c.pub_date = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time()))
	c.save()
	logout(request)
	return redirect('wangji.sharesite.snooker.snooker')
	# return render_to_response('sharesite/snooker.html',{'object':u}, context_instance=RequestContext(request))
	# return render_to_response('people/people_profile.html',{'object':u, 'site_list': site_list}, context_instance=RequestContext(request))

templates/people/people_detail.html
<html>

<link rel="stylesheet" type="text/css" media="screen" href="/static/css/site-detail.css">

<body>

<div id="wangji_screen">
<div id="header">	
  
  <div id="logo-floater">
     <h1>
	<a href="/" title="The Book of Web Business">
	  <img src="/static/image/logo.png" alt="The Book of Web Business" id="logo">
	  <span>The Book of Web Business</span>
 	</a>
	<span id="login-botton">
          <a href="/account/signup/" style="font-size=18px; margin-left=400px">退出</a>
	</span>
     </h1>
  </div>
  	
 </div>


<div id="wrapper">
 <div>

  <div class="topword"> 
	<strong>
	  {{ object.username }} 's Bookmarks
	</strong>
    <a class="btn-share" rel="nofollow" href="/sharesite/{{ object.id }}/add/">分享我的网页</a>
  </div>

{% for site in object.onesite_set.all %}
  <ul id="bookmarklist" class="bookmarks">
        <li class="post">
		  <div class="bookmark">
			<span></span>
			<div class="data">
			  <h4>
			   <a rel="nofollow" href="/sharesite/{{ site.id }}/">{{ site.title }}</a>	
			  </h4>	
			</div>
		  </div>
		  <h4>{{ site.info }}</h4>
	</li>
    </ul>
{% endfor %}
 </div>



 <div class="user-comments">
	<h3>网友评论,共有{{ object.messageboard_set.count }}条</h3>
{% for Message in object.messageboard_set.all %}
	<ul class="simple-list">
	  <li class="clearfix">
         <div class="comment">
			<div>
				<b>{{ Message.user }}</b>发表于 {{ Message.pub_date }}
			</div>
			<div>{{ Message.content }}</div>
   		 </div>
		</li> 
	</ul>
{% endfor %}

<form action="/people/{{ object.id }}/message/" method="post">
{% csrf_token %}
<h3>说点什么</h3>
<textarea name="info" rows="6" cols="60" required=true></textarea>
<input type="submit" value="保存" class="btn-submit">
</form>
 </div>
 </div>
 
</div>

</div>

</body>

</html>

templates/people/people_list.html
{% if object_list %}
    <ul>
    {% for object in object_list %}
        <li><a href="/people/{{ object.id }}/">{{ object.username }}</a></li>
		<h4>{{ object.password }}</h4>
		<h3>{{ object.id }}</h3>
    {% endfor %}
    </ul>
	
{% else %}
    <p>No objects are available.</p>
{% endif %}
<a href="/admin/">admin</a>

templates/people/people_profile.html
<html>

<link rel="stylesheet" type="text/css" media="screen" href="/static/css/site-list.css">

<link rel="icon" href="/static/favicon.ico" mce_href="/favicon.ico" type="image/x-icon">

	<script  type="text/javascript">
		function $(str) {
			return(document.getElementById(str));
		} 
		function isEmpty() {
			var db = 1;
			if ($("info").value == ""){
				db = 0;
			}

			if( !db ){
				alert("将您的信息输入完整吧!");
				return false;
			}
		}
    </script>

<body>

<div id="wangji_screen">

<div id="list_page">

 <div id="header">	
  
  <div id="logo-floater">
     <h1>
	   <a href="/" title="The Book of Web Business">
	     <img src="/static/image/logo.png" alt="The Book of Web Business" id="logo">
	     <span>分享您喜欢的网站，让网络生活丰富多彩...</span>
 	   </a>
       <span id="login-botton">
          <a href="/account/signup/" style="font-size=18px; margin-left=400px">退出</a>
	</span>
     </h1>
	 
  </div>
   	
 </div>
	
 <div>
  <div class="topsu">
    <div class="bd">
	 <div class="topsu-items">
	  <ul>
		<li class="firstli">
		  <strong>
	         {{ object.username }} 's Bookmarks
	      </strong>
		</li>
		<li>
		   <a href="/people/{{ object.id }}/saved">Saved</a>
		</li>
		<li>
		   <a href="/people/{{ object.id }}/share">Shared</a>
		</li>
	  </ul>
	</div>
  </div>
</div>

</div>

<div id="sidebar">
   <div class="sideGrp">
	 <div class="side-share">
		<a href="/sharesite/{{ object.id }}/add/"><h3 class="share_button" style="color: #4fd">分享我的网页</h3></a>
	 </div>
	 <div class="day-popular">
		 <div class="user-comments">
			<h3 class="day-shema">网友评论,共有{{ object.messageboard_set.count }}条</h3>
			
			<ul class="simple-list">
              {% for Message in object.messageboard_set.all %}
	  		 <li class="clearfix">
        	  <div class="comment">
				<div>
					<b>{{ Message.user }}</b>发表于 {{ Message.pub_date }}
				</div>
			    <div>{{ Message.content }}</div>
   		     </div>
		   </li> 
             {% endfor %}
	    </ul>


          <form action="/people/{{ object.id }}/message/" method="post" class="comment-form" onsubmit="return(isEmpty())">
	       {% csrf_token %}
		    <div>
				Comments
			</div> 
 
				<textarea id="info" name="info" rows="10" cols="20" required=true></textarea>


				<input type="submit" value="保存" class="btn-submit">

	     </form>
        </div>
	 </div>
   </div>
</div>


<div class="fb">  
    <ul id="bookmarklist" class="bookmarks">
    {% for object in site_list %}
        <li class="post first bookmark-0">
		  <div class="bookmark">
			<div class="title">
			  <h2>
			    <a rel="nofollow" href="/sharesite/{{ object.id }}/">{{ object.title }}</a>
	            <!--<a href="" class="edit-site">Edit</a>-->       
			  </h2>
			  <div id="title-fix">
				<span class="author">Published by <b>{{ object.user }}</b></span>
				<span class="comments">{{ object.comments_set.count }} 条评论 > </span>
			  </div>	
			</div>
			<div class="date">
			   <span>
					{{ object.pub_date.year }}
				</span>
			   <span>
					{{ object.pub_date.month }}.{{ object.pub_date.day }}
				</span>	
			</div>
		  </div>
	
		  <h4>{{ object.info }}</h4>
		<div> 
	       <a href="{{ object.domain }}" target="_black">
		    <div class="domain">
			  霸气顶入: {{ object.domain }}
		    </div>
  	       </a>
          </div>
		</li>
    {% endfor %}
    </ul>
</div>





</div>

<div class="footer">
    <h3>2011 Powered by <a href="http://mkdreamt415.appspot.com" target="_black">Weapon</a> @SJTU </h3>	
</div>



</div>
</body>
</html>